### ISSUE TITLE
Idea: lock test ether in a smart contract that requires work to unlock

### ISSUE THREAD

**Issue by mikebolt** [pk910/PoWFaucet#10]
Hi - this is not a bug or a feature request, but an idea for a related project.

I discovered this app today and I realized that a smart contract I wrote called [CrackableDeposit](https://github.com/mikebolt/smartcontracts#crackabledeposit) could be used as a PoW faucet. I'm not really sure what the advantage would be, but it would not require a server to operate the faucet, unless you wanted to have a server automatically deploy these contracts every hour.

The downside would be that users would have to already have some gas to call the withdraw function. And it costs more gas than your program because it has to pay gas to deploy a contract and users also have to pay gas. Your program only has to pay the gas for a simple transaction.

If you think this is a good idea then I could make a prototype web3.js app and host it on github pages. It would just need to know the address of any CrackableDeposit contracts that exist.

**Comment by pk910** [comment]
Heya @mikebolt,
Thanks for sharing your Idea :)

I've thought about the same thing when developing the faucet.
Basically the faucet just pays out some reward for finding hashes that start with a specific number of 0 bits.
The same can be done by a smart contract. it doesn't even need to be a new deployment for each "drop".

Unfortunately there are various drawbacks when doing it all on smart contract level:
1. As you've already pointed out, directly interacting with a smart contract requires some gas, so it is not suitable for new users that want to join the testnet and don't own any funds yet.
2. The mining work is only one part of the protection mechanisms that I've built into the faucet to fight against bots and farmers.
Another big part are IP-Based restrictions like the only-one-concurrent-session-per-IP limit, or the Proxy/VPN check that has a drastic effect on rewards when hit... 
It's unfortunately necessary to enforce these IP-based restrictions because I've already seen some guys spinning up hundreds of cloud machines to mine on my faucet and I can't support that due to limited funds.
3. To prevent the use of rainbow tables or any other form of pre-calculation there is a random salt for each session. 
That salt is not know before session start and only valid for 5h (max. mining time), so there is no way to pre-calculate or reuse hashes. 

I think such one-time crackable contracts are nice challenges to learn solidity specialties and things, but it's not really suitable for running a generic faucet. 
There are currently about 200 to 300 active sessions on the goerli faucet almost all time of the day and about 2000-3000 claim transaction each day.
Besides the fact that users would directly compete with each other to crack contracts (others working on the same contract would not get anything if anyone else was luckier), deploying that many crackable contracts would lead to a huge load on the chain which is not really helpful for anyone ;)

**Comment by mikebolt** [comment]
That all makes sense. Thanks for running this project.
