### ISSUE TITLE
Recurring limit

### ISSUE THREAD

**Issue by kkl6133** [pk910/PoWFaucet#134]
Hi I am confronting the following issue when mint goerliETH, with the notice below:

Could not start session, [recurring_limit] You have requested 3.04 Goeth in the last 5d.

However, I have not mint any for the last 2 days, what is the limit for the 3 days, I got confused. Is it 3GoerliETH limit for every 5 days? Thanks.

**Comment by pk910** [comment]
Heya @kkl6133,

There are currently 2 limits defined for the recurring_limit module on goerli:
* 3 ETH per 5 days
* 6 ETH per 14 days

These low limits are unfortunately necessary, because I'm very limited on goerli funds.
As GoETH got a value, whales are rather trying to make profit instead of funding faucets...

The limits are enforces per ETH & IP address. If you're sure you haven't been mining that amount in the last 3 days, there might be someone else with the same IP using the faucet.
Are you on a mobile network / behind carrier NAT?

Reminder: Goerli is deprecated and will be shut down soon.
Switch to holesky or sepolia for your testing activities :) 
Limits are much higher there.

**Comment by thangleta** [comment]
🤣

**Comment by kzml2850** [comment]
I am use mobile device and how to get you reffer ETH?
