### ISSUE TITLE
Convert "PoW" to useful mining ?

### ISSUE THREAD

**Issue by beadon** [pk910/PoWFaucet#14]
Given the number of people running this in a browser, is there a way to turn that work into a mining node to actually improve the network's performance ?

**Comment by pk910** [comment]
Heya @beadon,
Thanks for your suggestion :)

I agree, that the hashpower from this faucet could theoretically be used for something useful.
I've thought about some kind of real miner too, when I was starting this project.
There are actually libraries to do such browser mining easily - obviously not for any ETH chain as they're all secured by PoS now.

But I've decided to not go that way as it's seen very critical by the community.

I'm totally dependent on external fundings to run my faucet.
These fundings are granted due to the good will of some users and my agreements with goerli whales with the intention that I'm distributing these funds freely and without generating profit with it.
If I'd go the same way as other faucets who decided to take profits with their service, I wouldn't get any more coins to distribute..

Apart from that, it'd really be a huge implementation work to do such a change at this point in time.
Due to the fact that I'm not bound to any block template or so for the mining work, I've heavily used it to make the faucet tamper proof. Basically my own "block template", the client has to follow to be eligible for a reward and is easily verifiable by the backend.

**Comment by beadon** [comment]
Thanks for sharing the concept.  Yes, it wouldn't be to make a profit, just to make it available to do something valuable with the processing power (Donate to a good cause - the Red Cross? Do some protein folding for science?) What you've built is great, and I am very happy that it enables developers to use the network.

I'm partially writing because I'm in a bit of a bind right now, building out validators for SSV and in need of about 100 Goerli ETH for the team to test+build.  You may have noticed a few nodes hitting your service pretty hard over the past week; I've been examining the service closely!

**Comment by beadon** [comment]
Here's a little video of the absurdity I'm running.
https://share.vidyard.com/watch/8p1N9ghniF7q2YNKw2efp5?

Curious ...  I can't run more than 32 workers....  Intel's PCM reports that I could probably squeeze a little more out if I performance tune.

Also, a weird settling point to 700H/s regardless of the # of workers.

**Comment by pk910** [comment]
Yea, all this is intended to make the faucet more fair.

The 32 worker limit was there from the beginning, because enduser computers usually don't have more than 32 cores.
I've seen serve performance issues if the number of workers exceeds the number of CPU cores. 
These performance issues could lead to significant loss of mining rewards due to non-responding to websocket requests in time.
As that's very counterintuitive if the mining balance decreases when mining full speed, there is that limit to mitigate it.

Apart from that I've added a hashrate limit about 2-3 months ago.
It was introduced because I've seen some guy(s) mining excessively with multiple 2000 H/s machines over days.
It drained a significant amount of funds from the faucet at that time and made mining extremely hard for other users.
That's not my intension with "sharing fairly", so I've introduced a hashrate limit.
The limit is currently 700H/s, which is twice the average mining speed of all sessions that have used my faucet yet.

That limit is only one part of a big suite of protection methods.
It's quite effective in combination with the concurrency limit (1 session/IP), and other more secret limitations ;)

The faucet is definitely not intended to be used to gather hundreds of GoETH at that point in time.
Goerli is running out of funds and is already marked as deprecated.
Especially big projects like SSV should really consider to run their own testnet, so they're not affecting the regular public testnets too much. After all a public testnet is still a resource for everyone and not just specifically for your project.


I guess you've already noticed some serve reward reductions due to "farming" my faucet.
I'm not gonna share the exact details of these reward reductions that are applied "secretly" from background scripts when farmers or bots were detected ;)


I'm trying to give everyone a chance to get some GoETH from my faucet.
I know there is a huge need for bigger amounts of GoETH, but unfortunately I cannot fulfill them, as I'm very limited on funds too.

**Comment by beadon** [comment]
The mining limit makes complete sense if you consider how the hardware functions at a lower level.

There are real and virtual cores, the virtual cores (previously "hyperthreaded", or "threads" ) are only a way to use CPU cycles on the main core when the primary means of accessing the core is blocked due to I/O.  This has to do with how many CPU cycles are wasted in waiting for DMA controllers and other I/O subsystems like RAM and other devices to feed the CPU with information to process.

When the compute does not require I/O, then the threaded cores become completely useless.  The system "thrashes" context switching between proesses that are CPU-bound and competing for priority based on the scheduler.

Since the process, and whatever mechanism you have here appears to by CPU-bound, then the maximum number of cores to allocate will always be the number of real physical cores.  In Linux, you can look at /proc/cpuinfo and see how each "processor" has a "core_id" (the real core doing the processing), you can also see how many CPU cores are available by selectng "cpu_cores" to show how many are on-die for that processor -- examine the physical_id field if there are multiple dies.

Now that we've covered threading, the other thing for the system to not thrash itself to death - is giving enough CPU resource to the kernel, and related schedulers, interrupts, etc.  It's simple enough to redue the thread count of the CPU bound resource by 1 to give the kernel a chance to balance things correctly without context switching.   Using this method, you will never cross the maximum capabilities of the machine when the load is CPU bound.   This will result in the fastest "hash rate".   The same is true for compilations ( so many people think more threads is better, but in fact if you use this logic, your compiles will complete faster with fewer threads !).

So - if you want to protect people from themselves, there might be a way to spot this as an application running in a browser.  but, "32 threads" is just a blunt instrument to protect people -- if people are dumb enough to pile on the threads to their machine then I am on the opinion to let them screw up.  They'll see less ETH and learn a valuable lesson in performance tuning!

Just thought you might be entertained by this post.

Enjoy.
