### ISSUE TITLE
Github respo count

### ISSUE THREAD

**Issue by caliskan-u** [pk910/PoWFaucet#179]
Github repository count check fails...

**Comment by pk910** [comment]
Hi there,

Thank you for reaching out regarding the issue you've encountered with the faucet's GitHub repository count check.

It's important to note that the aggregations of GitHub profile data, including repository counts, are cached for a period ranging from several hours to a few days. This caching process is crucial to minimize the number of API requests made to GitHub. Without it, the faucet could face rate limiting by GitHub, which would impact its functionality for everyone.

Additionally, when aggregating your repository count, we only include repositories that you have personally created. Forked repositories, copies, or repositories without any content (empty repositories) are not counted towards your total.

If your recent repository activities aren't reflected in our system yet, it's likely due to this caching. We appreciate your patience and understanding as the data updates according to the cache refresh cycle.
