### ISSUE TITLE
Send ERC-20 tokens - The Faucet is currently not working properly (RPC error)

### ISSUE THREAD

**Issue by air3ijai** [pk910/PoWFaucet#184]
We are trying to setup a faucet to send ERC-20 token deployed on the [Clique PoA network](https://geth.ethereum.org/docs/fundamentals/private-network#clique) and have some question with that
1. Is there a way to send native token with the erc-20 one?
    To be able to make a transaction using a token, we would need some native tokens. Is there a way to send both at the same time?
2. When we set `faucetCoinType: "erc20"` we see errors in the app
   ```
   2024-04-07 08:06:39  ERROR    ### Caught unhandled rejection: ContractExecutionError: Error happened while trying to execute a function inside a smart contract
     Stack Trace: ContractExecutionError: Error happened while trying to execute a function inside a smart contract
       at Web3RequestManager._isReverted (/app/bundle/powfaucet.cjs:89302:19)
       at Web3RequestManager._processJsonRpcResponse (/app/bundle/powfaucet.cjs:89248:42)
       at Web3RequestManager.<anonymous> (/app/bundle/powfaucet.cjs:89147:29)
       at Generator.next (<anonymous>)
       at fulfilled (/app/bundle/powfaucet.cjs:89017:58)
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   ```
   Is there a way to pass our token smart contract ABI?

**Comment by pk910** [comment]
Heya @air3ijai,

There is currently no way to send both, a ERC20 & native funds at the same time.
It'd be quite complex to add support for such scenarios as there are quite many settings in the faucet that refer to amounts that are specific to the token.
So to add proper support, there would need to be some kind of configurable factor that defines the balance between native & ERC20 amounts...

I think I'd rather run 2 instances of the faucet, one for the native token & one for the ERC20.

However, I can give you some Ideas I have in mind how to support such scenarios:
1. Easiest: Run 2 instances.
2. You could create a fork of the faucet and patch the relevant code to drop both tokens.
The relevant code for sending funds to users is here: https://github.com/pk910/PoWFaucet/blob/master/src/eth/EthWalletManager.ts#L325-L328
Unfortunately there is more to change to get the nonce calculation right again when using 2 transactions for each claim instead of only 1... So I'd only recommend that approach if you have some typescript experience ;)

3. You could create a custom contract that handles the distribution and sends both tokens to the user.
When using `faucetCoinType: "erc20"`, the faucet just calls the `transfer` function of the provided contract addess to transfer funds.
The distribution contract could add custom logic and send both, native & ERC tokens.
I've implemented an example:  https://gist.github.com/pk910/a94769a27f57631c030989229bd51cab
  This is completely untestet,  but if it works as intended, you'd just need to:
  * deploy the contract with the address of the ERC20 you want to distribute & the wallet address of the faucet
  * set `faucetCoinContract` in the faucet config to the distribution contract
  * fund the distribution contract with native funds & ERC20 tokens.
The faucet wallet still needs some funds for gas fees,  but the distibutable funds need to be in the distributor contract.



Besides of that, the error you've send indicates that the transaction was reverted on chain.
Check if the `faucetCoinContract` address is correct and the faucet wallet holds some of the ERC20 tokens :)

**Comment by pk910** [comment]
> Is there a way to pass our token smart contract ABI?
There is no way to set custom abi's. The faucet assumes a standard ERC20 contract.
If your token is different, I'd suggest looking at the distributor contract above :)

**Comment by air3ijai** [comment]
Thank you for the suggestions, will try to implement that later and now trying to run 2 separate wallets with `native` and `erc20`.

```yaml
faucetTitle: ETH / Token
faucetSecret: 0x12345...
faucetCoinType: native / erc20
faucetCoinSymbol: ETH / Token
faucetCoinContract: "" / 0x2345...
```

We use same `faucetSecret` and ETH instance detect the balance, but the token one does not. Account contains the token and I [check](https://github.com/gochain/web3/discussions/265#discussioncomment-9057939) that.
```shell
# ETH
2024-04-09 13:55:58  INFO     Wallet 0x7d46Dd2008157901011A7598a73BDB34A2ea6E4d:  99999998.837 ETH  [Nonce: 5]

# Token
2024-04-09 13:55:40  INFO     Wallet 0x7d46Dd2008157901011A7598a73BDB34A2ea6E4d:  0 Token  [Nonce: 5]
```

Should we consider to adjust any other settings?

**Comment by pk910** [comment]
You cannot use the same wallet for both instances of the faucet or you'll see transactions replacing each other.
Each instance should have its own wallet.

Apart from that, the balance of your ERC20 instance doesn't look good..
I'm not sure where it comes from, but I guess it's related to the ERC20 token contract.

Do you have a public RPC endpoint so I can have a look myself?
Otherwise, please share the ABI of your token :)

**Comment by air3ijai** [comment]
Setup two different accounts for the ETH and Token and shared and ABI - https://pastebin.com/1PqPjKic

**Comment by air3ijai** [comment]
@pk910, I just was able to run local configuration, but faucet still can't detect ERC20 token balance - `0 TEST  [Nonce: 0]`

<img width="859" alt="Screenshot 2024-05-20 at 19 45 49" src="https://github.com/pk910/PoWFaucet/assets/88528265/2e19b3e5-747e-491d-bae6-781f5ea3ed37">

<details>
<summary>More details</summary>

 1. Run local [PoA network based on Geth](https://geth.ethereum.org/docs/fundamentals/private-network)
 2. Deployed ERC20 token using [gochain/web3](https://github.com/gochain/web3?tab=readme-ov-file#generating-common-contracts) - they are using [openzeppelin-contracts](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/token/ERC20)
    ```shell
    export WEB3_RPC_URL=http://localhost:8545
    export WEB3_PRIVATE_KEY=0xab9a687173bf9b929a262fbe7325766fc4653564b80f4fcd333e36a24c739f1f

    # Generate contract
    web3 generate contract erc20 --name "Test Tokens" --symbol TEST

    # Build contract
    web3 contract build TEST.sol

    # Deploy contract
    web3 contract deploy TEST.bin
    ```

 3. Minted some tokens
    ```shell
    TOKEN_ADDRESS=0xC922D545C09eC80f21a60D6a6ba0A9AB94D9320F
    FAUCET_ADDRESS=0x3780a7E5434F0a043f4eaff3D9e49D502c68aB22

    # Mint token
    web3 contract call \
      --wait \
      --abi TEST.abi \
      --gas-limit 800000 \
      --address $TOKEN_ADDRESS \
      --function mint $FAUCET_ADDRESS 5000000000000
    ```

 4. Sent navite token
    ```shell
    # Send native tokens
    web3 transfer 5000 to $FAUCET_ADDRESS
    ```

 5. Checked faucet balance
    ```shell
    # ERC20
    web3 contract call \
      --abi erc20 \
      --address $TOKEN_ADDRESS \
      --function balanceOf $FAUCET_ADDRESS

    5009000000000

    # Native
    web3 balance $FAUCET_ADDRESS

    5000
    ```

    Similar numbers we can see in the explorer
    <details>
    <summary>screenshot</summary>

    <img width="1240" alt="Screenshot 2024-05-20 at 19 33 11" src="https://github.com/pk910/PoWFaucet/assets/88528265/850cb3cb-30ae-41e0-b2bc-a9c1a8ff149e">
    </details>
</details>

How we can debug this?

**Comment by air3ijai** [comment]
The issue was related to the `decimals`. It was required to send `50,000,000,000,000,0000,000` tokens.

Now, faucet show `5 TEST` tokens
<img width="848" alt="Screenshot 2024-05-21 at 14 59 55" src="https://github.com/pk910/PoWFaucet/assets/88528265/ac585d5d-afe8-4364-8ff7-e2ebecc85e6a">

**Comment by air3ijai** [comment]
We followed the first proposal `Easiest: Run 2 instances` and 2 separate Faucets works well.

Will check [Distributor.sol](https://gist.github.com/pk910/a94769a27f57631c030989229bd51cab) slightly later.
