### ISSUE TITLE
claim txs are running oog

### ISSUE THREAD

**Issue by gosuto-inzasheru** [pk910/PoWFaucet#2]
eg see `0x6a188e722af1aa641dd0f04f3a0accbd15f89ebd3d6790fd4d4961cb5d5c5f49` or `0x09c7e501dd4979831ad515a7df4d11f5c737afd05730b91244957d72a8eea0cc`

**Comment by pk910** [comment]
Hi @gosuto-inzasheru,
Thanks for your report. I've sent you the missed reward manually.

The transactions you've mentioned failed because they ran out of gas. That is a wanted limitation of the faucet to prevent payouts to contracts. 
Contracts are unfortunately often used by bots or farmers to deploy forwarders and evade address based restrictions of the faucet...

I've implemented a additional check to prevent new sessions for contract addresses to make that more clear.

You'll need to mine to a normal wallet and transfer the mined funds to your Gnosis Safe wallet afterwards.

**Comment by gosuto-inzasheru** [comment]
thank you for your quick response and awesome project!!! keep up the good work 🙏
