### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'ipflags')

### ISSUE THREAD

**Issue by ndcc5** [pk910/PoWFaucet#232]
TypeError: Cannot read properties of undefined (reading 'ipflags')

How to slove?

**Comment by pk910** [comment]
Can you please give more context?
- Where do you see the error? 
- What have you tried doing that triggered the error?
- Are you running the faucet yourself or did you get that error on one of my public instances?
- If running yourself, please provide a copy of your config (censor the private keys!)

**Comment by ndcc5** [comment]
It is caused by IP. This prompt will not be given after changing IP.

**Comment by Diablo772-lab** [comment]
I don't know what happened. I entered my metamask wallet address which I usually use for the holesky faucet but today I couldn't anymore because there was a notification "[CONCURRENCY_LIMIT] Only 1 concurrent session allowed per IP". Usually after I finish transferring Holesky faucet tokens I immediately press return and I can mine as usual but now I can't anymore. so what should i do sir can you help me???
this is my metamask wallet address: 0x32915B6964d34d364b72041908c8a2A6AcFF8AA3
