### ISSUE TITLE
Boost is not working

### ISSUE THREAD

**Issue by Mouradif** [pk910/PoWFaucet#25]
Hi,

I've linked a bunch of socials to get boosted rewards:

![image](https://user-images.githubusercontent.com/4118825/227555740-dc8b3552-0b1d-49c2-8c25-e998e6467c8e.png)

But I still get 0% boost:

![image](https://user-images.githubusercontent.com/4118825/227555840-76e64db9-f925-44aa-bff9-65852f07b09d.png)

At first I thought maybe it's a UI not updating thing but after an hour of hashing, I saw that no boost was applied

**Comment by pk910** [comment]
Heya,

That's strange.
Your first screenshot indicates that your passport has been loaded & applied successfully otherwise this summary wouldn't been shown.
The second one obviously says "no boost" :D

Is that the same session? 
Or are these screenshot made from different sessions / maybe with different target addresses?
