### ISSUE TITLE
clouds

### ISSUE THREAD

**Issue by Dosarii** [pk910/PoWFaucet#27]
Is it possible to get money and a reward for this work? I have a limited number of these deposits. Do I benefit and thank you for this faucet, and is there a faucet dedicated to agriculture

**Comment by pk910** [comment]
> Is it possible to get money and a reward for this work?

Well, the reward is the GoETH amount you've mined.
There is no other reward and the faucet is not working on anything useful in behind.


> is there a faucet dedicated to agriculture

Hahaha, I like that expression :D
I guess it's because I'm using the term "farmer" as a reason to kick out various sessions.
But it's actually not against people that work in agriculture as a farmer. 

In crypto world, "Farmer" is used to describe someone who (ab)uses a tool systematically to get as much funds as possible.
Farming my faucet means that someone runs multiple sessions in parallel, or orders a large amount of cloud machines for mining or so...

Due to the fact that goerli is running out of funds and there are no more free funds available, I cannot support farming activity on my faucet.
I'm trying to distribute the remaining funds as fair as possible.

And to answer your question: No, I don't think there is any faucet that allows farming activities.
If you need a bigger amount of funds, you'll need to buy them from the open market.

**Comment by Dosarii** [comment]
Well, the reward is the GoETH amount you've mined.
There is no other reward and the faucet is not working on anything useful in behind

Thanks for your reply and I appreciate what you are doing but I have no idea how to withdraw the amount from the GoETH wallet

**Comment by pk910** [comment]
Yea, it's basically not intended to be withdrawn.

The faucet is intended to help developers who want to deploy or test their contracts on goerli.
This kind of activity normally only requires a very small amount to pay gas fees.
So it's enough to use my faucet, instead of buying funds with real money.

It's definitely not intended for the other way round.
The small amount will not be enough to trade it for a reasonable amount of real ETH & bridging it to mainnet.
(Why should I distribute my funds freely for doing that? If that would be the intention, I'd probably just trade the whole faucet balance myself :D)
