### ISSUE TITLE
Payment queue not moving (Sepolia)

### ISSUE THREAD

**Issue by sameignatovich** [pk910/PoWFaucet#296]
Hi!

I just realized that my reward from last night has not been received. I see that the last transaction from the faucet address was made 7 hours ago.

It seems something went wrong with the reward processing. Could you please investigate?

**Comment by pk910** [comment]
Heya @sameignatovich 

Thanks for the report, yea, I see there are currently about 2.5k claims queued.
That's due to the enormous base fee on sepolia right now.
The faucet will not pay more than 500 Gwei per gas for a transaction, but the base fee is currently at about 2000 Gwei per gas :D

Pending claims will be processed as soon as the network base fee goes below 500 Gwei again.

**Comment by pk910** [comment]
I've added a notification banner to the faucet to explain that behavior.
Might be worth adding some logic to show that banner automatically when the fee is too high

**Comment by sameignatovich** [comment]
Thanks for explanation!
