### ISSUE TITLE
Can I buy some Goerli ETH?

### ISSUE THREAD

**Issue by Mouradif** [pk910/PoWFaucet#30]
I've been mining for 2 days and it covered for one contract deployment...

I will buy Goerli ETH for Mainnet ETH if someone's willing to sell. @pk910  maybe? I need like 50 Goerli ETH, how much would that cost?

**Comment by pk910** [comment]
I'm not selling goerli eth here.
Testnet funds should be free as it's totally against the concept of a testnet to have a value on its tokens...
But yea, I understand the need to get more funds more quickly.

There is a testnet bridge where you can buy Goerli funds (https://testnetbridge.com/).
But again: It's totally against the concept of a testnet ;)

Goerli is deprecated because it is running out of funds and it will be shut down at the end of the year.
You should take a look at sepolia, which is be a better place to deploy & test contracts :)

**Comment by Mouradif** [comment]
I agree, they should be free. As of now, they're not. they a lot of cost energy (0.2 eth per hour on a 12th Gen Intel(R) Core(TM) i9-12900KF   3.20 GHz running with 24 workers) and with current gas prices, I need 1.5 eth to deploy a contract (it's a big one but still under the size limit).

Thanks for the link, it's perfect for my desperate situation
