### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'ipflags')

### ISSUE THREAD

**Issue by VanderDT** [pk910/PoWFaucet#302]
![Monosnap Sepolia PoW Faucet и еще 2 страницы — Лич](https://github.com/user-attachments/assets/d80de7fa-3b0f-46fb-8516-b0d44f8294f5)

Does not work (

**Comment by pk910** [comment]
Heya @VanderDT,
Thanks for your report :)

I've found & fixed the issue that's causing this weird error message. 
However, the issue was in the frontend code, that was about to show another error message that was coming from the server.
So yea, fixing the frontend part will hopefully show the "real" error message now.

I've reopened the issue as it's been accidentally closed by the code change.
This is not rolled out to the public instances yet. I'll keep this issue updated once it's rolled out.

**Comment by 841660202** [comment]
+1
