### ISSUE TITLE
This seems to take longer than usual... You can close this page now. Your claim is queued and will be processed as soon as possible.

### ISSUE THREAD

**Issue by BuingBuing** [pk910/PoWFaucet#36]
i used infura RPC but I Claim Mining Rewards  give me hints This seems to take longer than usual... You can close this page now. Your claim is queued and will be processed as soon as possible.

**Comment by pk910** [comment]
Heya,
I guess you're running your own instance?
Did you transfer some funds to the faucet wallet?
The faucet does not generate new coins. It's just distributing the funds from the faucet wallet.

Does the log show any errors?

**Comment by BuingBuing** [comment]
> 嘿， 我猜你在运行自己的实例？ 您是否将一些资金转移到水龙头钱包？ 水龙头不会产生新的硬币。它只是从水龙头钱包中分配资金。
> 
> 日志是否显示任何错误？


ethRpcHost is an api I applied for myself, but there is no error in the log

**Comment by BuingBuing** [comment]
> 嘿， 我猜你在运行自己的实例？ 您是否将一些资金转移到水龙头钱包？ 水龙头不会产生新的硬币。它只是从水龙头钱包中分配资金。
> 
> 日志是否显示任何错误？



> Heya, I guess you're running your own instance? Did you transfer some funds to the faucet wallet? The faucet does not generate new coins. It's just distributing the funds from the faucet wallet.
> 
> Does the log show any errors?

ethRpcHost is an api I applied for myself, but there is no error in the log

**Comment by pk910** [comment]
If you've only changed that one setting in the config that's not enough.
You should at least provide your own key for `ethWalletKey`.
That's the private key for a normal ETH address. 
You need to send some funds to this wallet and the faucet will then send out rewards from there.

**Comment by pk910** [comment]
The faucet should also display its wallet address and balance on startup.
There should be a line like that:
```
2023-04-29 20:02:13  INFO     Wallet 0x917c0A57A0FaA917f8ac7cA8Dd52db0b906a59d2:  7.133 ETH  [Nonce: 213]
```

**Comment by BuingBuing** [comment]
> ethWalletKey

ethWalletKey Is this private key obtained from the API I applied for?

**Comment by BuingBuing** [comment]
> 水龙头还应在启动时显示其钱包地址和余额。
> 应该有这样一行：



> 水龙头还应在启动时显示其钱包地址和余额。 应该有这样的一行：
> 
> ```
> 2023-04-29 20:02:13  INFO     Wallet 0x917c0A57A0FaA917f8ac7cA8Dd52db0b906a59d2:  7.133 ETH  [Nonce: 213]
> ```

yes it did appear this        Wallet 0xCA9456991E0AA5d5321e88Bba44d405aAb401193:  0 ETH  [Nonce: 42]      Do I need to change the address of this Wallet?

**Comment by pk910** [comment]
No. That API key is part of the `ethRpcHost`.
So for infura that would be:
```
ethRpcHost: "https://eth-goerli.g.alchemy.com/v2/pi***censored key***cQ"
```

The `ethWalletKey` is the private key for the wallet.
In your case it looks like you haven't modified that setting.
The dummy key I've put in there (that `feedbeef1234`-key) is the private key for `0xCA9456991E0AA5d5321e88Bba44d405aAb401193`.
So your faucet instance tries to distribute rewards from there.
That fails because that wallet is empty: https://goerli.etherscan.io/address/0xCA9456991E0AA5d5321e88Bba44d405aAb401193

However, you shouldn't use that key, as it's very insecure ;)
Create your own wallet eg. via metamask and export the private key from there.
Or use a online tool like that: https://privatekeys.pw/keys/ethereum/random

You then need to send some funds to that wallet.
Again: The faucet is not able to generate new coins ;)
