### ISSUE TITLE
Getting Error of Limit

### ISSUE THREAD

**Issue by RobeelZahid111** [pk910/PoWFaucet#54]
Hello there 
I am getting popup message of Limit 
It Says You have claimed 3.48 GETH in last 5 days 
I am mining the faucet for the Linea Project 
Please change this limit it is urgent

**Comment by pk910** [comment]
Heya,
I can't remove this limitation because goerli is running low on funds.
The faucet can only distribute 1000 ETH every day and there are thousands of sessions trying to get some part of it.

As the error message said, you've already got ~3.5 GoETH. That should be enough to do any kind of testing.
I guess you're trying to "farm" an airdrop to get more than others by doing the airdrop requirements multiple times?
If so,  you've answered the question why this limit is necessary yourself :P

**Comment by RobeelZahid111** [comment]
Okay thanks for answering When I will be able to get faucet again ? 
I have been using this for Linea Task week 8 which require too much Goerli Eth
