### ISSUE TITLE
Blocks Erroneously Defined Russian IP Addresses

### ISSUE THREAD

**Issue by woodydeck** [pk910/PoWFaucet#58]
It's absolutely bollocks to ban anyone from anywhere on a testnet. This is decentralization, and the world is more free when we resist tyranny together. Banning Russian IPs because you support imperialists/neo-Nazis in Ukraine is irrelevant. You shouldn't be restricted either for these views. Decentralization doesn't care about your politics. We get it, you support the pogroms and long running genocide there against Jews, Tatars, and Roma, and want to gatekeep who is considered a Ukrainian. That's fine, just leave your political views out of Web3. 

It's already a shitshow to get testnet Ether. Don't make it worse.

**Comment by pk910** [comment]
Sorry, this is not for discussion.
I'm a german entity, running this faucet on a german domain, hosted on a german server.
There are various export restrictions for all kinds of material & financial goods (including cryptocurrency) in place from my jurisdiction against russia.
I'm already in a gray-zone with distributing valuable goods in exchange for hashrate, which can be seen as some kind of "trade" too.
There are various other faucets available on https://faucetlink.to/goerli. Please use one of these.

**Comment by M2l2koPOWER** [comment]
I don't think Github is the right place to make political statements, so I'll only comment on the immediate problems with faucet.

I'm not quite sure if you are in Finland, otherwise why would you need a VPN for a faucet? Especially considering that Hetzner has servers in Finland, and their IPs are blocked (like other hosting sites) in faucet to protect against any bots (not Russian people). Also, you haven't shown exactly what error you're seeing, so I'm assuming the blocking happened either because of the hosting IP factor, or your shadowsocks and wireguard just aren't working, lol.

Just try a different VPN, dude. Eto ne dolzno bit' bolshoy problemoy dlya nas ;)
