### ISSUE TITLE
Problem with queue

### ISSUE THREAD

**Issue by LastSkywalkerER** [pk910/PoWFaucet#75]
I have mined 7.5 Sepolia, but faucet said me, that i am 2500-3000th in queue and it lasts all day. Last transaction from faucet wallet was a day ago. Where is my Sepolia?! Fix your nonce please)

**Comment by maloiMASLACH** [comment]
same issue

**Comment by Fuffes** [comment]
Same issue

**Comment by pk910** [comment]
yea, looks like the transaction queue got stuck for some reason...
I'm looking into it :)

No rewards should be lost.. They're just delayed "a bit"

**Comment by pk910** [comment]
Issue Recap:
This is unfortunately a problem with the web3js library.
It looks like the library is not handling HTTP errors properly in v4.

When a HTTP error with non-proper JSON response occurs, the library throws an unhandled promise rejection instead of propagating the error back to the caller...
The caller gets stuck forever as the result promise from web3js never resolves.

I've implemented a workaround for this bad behavior in 3699bc82aa01e1ec98a26fe5ebe4272f94a9dd6b

The faucet introduces a timeout for these web3js calls now,  so I'm rejecting the result promise when it doesn't get resolved/rejected by the library in time.

**Comment by LastSkywalkerER** [comment]
you are Web3 GOD, thanks
