### ISSUE TITLE
hCaptcha verification failed

### ISSUE THREAD

**Issue by xyokube** [pk910/PoWFaucet#8]
Hello,

Congrats on the great work.

When deploying your code, I have nonetheless an issue with hCaptcha. 
The captcha is rendering well on the website, I can click and pass the test, excluding a problem related to a missing site-key/secret-key (as the statistics are updating correctly on my hCaptcha dashboard).

When clicking on "Start Mining", hence triggering "onStartMiningClick()", I systematically fall into an Exception with the variable "close " containing the code 'INVALID_CAPTCHA' and the message "Captcha verification failed".

Then, the window "Could not start session." (className='alert alert-danger') is opening with the message stated above.

All the best,
xyokube

**Comment by xyokube** [comment]
Many thanks for your fast response.

ReCaptcha works without any problem.

Nonetheless, hCaptcha still not - even by regenerating a new website key. I also doubled check the secret key, making sure "0x" was well copied, but ultimately, I get the same error.

Best,
xyokube

**Comment by pk910** [comment]
Hmm, that sounds very strange.
I don't really believe the token gets amended somewhere in the flow as the implementation works fine for me.
Anyway I'm happy to be proven wrong :D

Can you add a `console.log("Captcha verification: ", token, remoteIp)` in src/services/CaptchaVerifier.ts on line 24 (before hcaptcha.verify)?
Then it should print out the exact token that was generated by the hcaptcha UI component.
Checking that token manually via the "hcaptcha.com/siteverify" api should give you the same result...

**Comment by xyokube** [comment]
I like the mentality!

Well, my second question would have been "where in the code does the captcha get verified, because I didn't find any "footprint" of the verifier. And the answer is as strange as you underlined it: src/services/CaptchaVerifier.ts exists in the Docker image that I have (as it gets deployed on the server) **but** does not appear anywhere in the website "tree" (when I do "inspect/F12").

**Comment by pk910** [comment]
Yea, that's as expected.

There are three independent project packages in this repository:
* the root folder (end especially `/src`) is the server side code, that is run on the server to serve the backend api / websocket server.
* the `/faucet-client` folder is the client side code that gets built into a js bundle and delivered on the browser
* the `/faucet-wasm` folder contains crypto related stuff and gets built into a wasm file that is loaded by server & client side code

`/src/services/CaptchaVerifier.ts` is part of the server side code and is the part of the code that does the verification of a captcha token that was send by any client.
The initial error is triggered when this verification on line 24 fails.

If I understood your previous message correctly you have already manually verified the token that is generated by the client side UI?
With the `console.log` command above you should be able to see the actual token that the backend tries to verify. 
If your assumption is right that token is different from the one that was generate on client side and you've proven to work.

Hmm, with docker it's harder to debug, are you familiar with attaching to a shell within the container?
If so you can manually add the log line there and start the faucet again with  `npm run start`
Otherwise I'd recommend running it without docker. You just need a linux based machine with node/npm installed.

**Comment by pk910** [comment]
Due to your issue I tried debugging it in docker myself, so I've noted the wrong commands in the README..
Fixed now: https://github.com/pk910/PoWFaucet/commit/3ec287b516b662e976b5b018c4139c6eb8bfd9db

Apart of that my test docker deployment works fine with hcaptcha:  http://65.109.130.80:8080/

**Comment by xyokube** [comment]
Funny .. I did the `console.log("Captcha verification: ", token, remoteIp)` you suggested, I do obtain my token as expected followed by:
`[2022-11-24 00:44:47] 2022-11-24 00:44:47  INFO     Returned error to client: [INVALID_CAPTCHA] Captcha verification failed`

**Comment by pk910** [comment]
can you compare the token you see in the log with the one that is generated by the ui?
You can get the token on UI side via `document.querySelector(".faucet-captcha iframe").getAttribute("data-hcaptcha-response")` in the debugger tools :)

If it's the same (as I expect) there must be an issue with the hcaptcha control/token/keys/?

**Comment by xyokube** [comment]
Alright!

So, I almost got the same output between `console.log("Captcha verification: ", token, remoteIp)` and `document.querySelector(".faucet-captcha iframe").getAttribute("data-hcaptcha-response")`. But obviously, in the first case, I got an extended string, because of `remoteIp`. 
I had the idea to shorten line 24 in src/services/CaptchaVerifier.ts, turning it simply to `let hcaptchaResponse = await hcaptcha.verify(faucetConfig.captchas.secret, token);` as per the use case provided in the Captcha readme in "node_modules", and **now it works perfectly well!**

Many thanks again pk910,
Have a good night in Germany,
xyokube

**Comment by pk910** [comment]
Hmm, that's very interesting.

I've added  remoteIp & siteKey to the verification query. 
These are optional, but  why not  ¯\_(ツ)_/¯

I didn't ever notice a verification miss because of that. 
Is there anything special in your setup that could explain why it fails?  
I guess it's due to the remoteIp parameter - are you using private IPs?

**Comment by xyokube** [comment]
I have no idea what in my setup could explain that - but definitely the source of the (ex) problem - especially since ReCaptcha was working well (but the verify query was built differently there).

On another note (:D), now that I was able to move forward, I get a `Stack Trace: Error: ENOENT: no such file or directory, open '/config/faucet-store.json'`.
I surely noticed your comment about modifying faucet-config.yaml to incorporate:
`faucetStore: "/config/faucet-store.json"
faucetLogFile: "/config/faucet-events.log"`
But these two files are simply nonexistent on my end. did they got lost on update? (as you suggested it could happen)

Would you like me to do a new issue ticket for this?

Many thanks again,

**Comment by pk910** [comment]
Hmm, these files don't need to exist upfront. They're created if not.
Can you paste the full error including trace (source file/line number of the error)?

Is the /config/ directory within the docker container writable? 
That directory should be mapped into docker, so it might be related to the permissions of the folder that is used as target on the host system

**Comment by pk910** [comment]
Yea, that's pretty much what I expected here. 
The error is triggered when the faucet tries to save one of the files (so it tries to create that file).

Can you check the `-v /home/powfaucet:/config` parameter of the docker run command?
It should point to a location that is writeable.  
Can you also try to chmod that folder to 0777 permissions (writeable to everyone)?
I guess the folder is owned by another user / has too less permissions, so the faucet can't write to it.

**Comment by xyokube** [comment]
So, I confirm there was no error in local development, but the problem probably came from the deployment in DigitalOcean where the location was not writeable. In fact, I could not even find /config in the directory.
By switching the location to /app, for example, the file has been successfully created.

Again, I would like to thank you for the time & effort,
xyokube
